# Generated by Django 4.2.30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('portfolio', '0003_project_presentation'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('referrer', models.CharField(blank=True, max_length=500)),
                ('user_agent', models.CharField(blank=True, max_length=500)),
                ('device_type', models.CharField(choices=[('desktop', 'Desktop'), ('mobile', 'Mobile'), ('tablet', 'Tablet'), ('other', 'Other')], default='other', max_length=10)),
                ('browser', models.CharField(blank=True, max_length=40)),
                ('operating_system', models.CharField(blank=True, max_length=40)),
                ('session_key', models.CharField(max_length=40)),
                ('ip_hash', models.CharField(blank=True, max_length=64)),
                ('is_new_visitor', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='PortfolioEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('project_click', 'Project link click ("View Project")'), ('presentation_download', 'Presentation download'), ('book_meeting_click', 'Book a Meeting click'), ('send_email_click', 'Send Email click')], max_length=30)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('path', models.CharField(blank=True, help_text='Page the click happened on', max_length=255)),
                ('session_key', models.CharField(blank=True, max_length=40)),
                ('ip_hash', models.CharField(blank=True, max_length=64)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analytics_events', to='portfolio.project')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='pagevisit',
            index=models.Index(fields=['timestamp'], name='analytics_pv_timestamp_idx'),
        ),
        migrations.AddIndex(
            model_name='pagevisit',
            index=models.Index(fields=['path'], name='analytics_pv_path_idx'),
        ),
        migrations.AddIndex(
            model_name='pagevisit',
            index=models.Index(fields=['ip_hash'], name='analytics_pv_ip_hash_idx'),
        ),
        migrations.AddIndex(
            model_name='pagevisit',
            index=models.Index(fields=['session_key'], name='analytics_pv_session_idx'),
        ),
        migrations.AddIndex(
            model_name='portfolioevent',
            index=models.Index(fields=['timestamp'], name='analytics_pe_timestamp_idx'),
        ),
        migrations.AddIndex(
            model_name='portfolioevent',
            index=models.Index(fields=['event_type', 'timestamp'], name='analytics_pe_type_ts_idx'),
        ),
        migrations.AddIndex(
            model_name='portfolioevent',
            index=models.Index(fields=['project', 'event_type'], name='analytics_pe_proj_type_idx'),
        ),
    ]
