# Generated by Django 4.2.30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_contactmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='presentation',
            field=models.FileField(blank=True, help_text='Optional — a slide deck / presentation file (PDF, PPTX, etc.) visitors can download.', null=True, upload_to='project_presentations/'),
        ),
    ]
